### ISSUE TITLE
[BUG][Potential] server up for a while and then panic 

### ISSUE THREAD

**Issue by jiekun** [deepflowio/deepflow#3891]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Server

### What you expected to happen

When deploying the self-builded DeepFlow server, it ran into panic after a few seconds. It MIGHT caused by the existing issue in main branch but I cannot locate the root cause.

I am trying to post the log here and see if it could be reproduced by other developers.

Kubernetes log I got:
```
2023-08-16 16:37:31.129 [INFO][0m [trisolaris/synchronize] tsdb.go:64 ctrl_ip is 127.0.0.1, (platform data version 1692174879 -> 0), (acl version 3692174879 -> 0), (groups version 1692174879 -> 0), NAME:server-pod-names-watcher
2023-08-16 16:37:31.141 [INFO][0m [clickhouse.client] client.go:197 query_uuid: a638e9f1-822e-434e-b481-0492fc696c47. query api statistics: 0 rows, 2 columns, 0 bytes, cost 1.000000 ms
2023-08-16 16:37:31.142 [INFO][0m [clickhouse.client] client.go:197 query_uuid: a638e9f1-822e-434e-b481-0492fc696c47. query api statistics: 0 rows, 2 columns, 0 bytes, cost 0.000000 ms
2023-08-16 16:37:31.143 [INFO][0m [clickhouse.client] client.go:197 query_uuid: a638e9f1-822e-434e-b481-0492fc696c47. query api statistics: 0 rows, 3 columns, 0 bytes, cost 0.000000 ms
2023-08-16 16:37:31.405 [INFO][0m [trisolaris/synchronize] tsdb.go:64 ctrl_ip is 192.168.49.2, (platform data version 1692174879 -> 1692174879), (acl version 3692174879 -> 0), (groups version 1692174879 -> 1692174879), NAME:ingester
2023-08-16 16:37:31.405 [INFO][0m [trisolaris/synchronize] tsdb.go:75 ctrl_ip:192.168.49.2, cpu_num:16, memory_size:33347633152, arch:x86_64, os:alpine 3.18.3, kernel_version:5.15.0, pcap_data_mount_path:<nil>
2023-08-16 16:37:32.118 [INFO][0m [trisolaris/synchronize] tsdb.go:64 ctrl_ip is 127.0.0.1, (platform data version 1692174879 -> 0), (acl version 3692174879 -> 0), (groups version 1692174879 -> 0), NAME:resource-info-watcher
2023-08-16 16:37:32.118 [INFO][0m [event.decoder] grpc_resource_info.go:156 Event update rpc platformdata version 0 -> 1692174879
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xa92dac]

goroutine 2683 [running]:
github.com/deepflowio/deepflow/message/trident.(*PrometheusTargetResponse).MarshalToSizedBuffer(0x0, {0x9bc5780, 0x0, 0x0})
	/home/jiekun/repo/github.com/deepflow/server/vendor/github.com/deepflowio/deepflow/message/trident/trident.pb.go:13659 +0x2c
github.com/deepflowio/deepflow/message/trident.(*PrometheusTargetResponse).Marshal(0x0?)
	/home/jiekun/repo/github.com/deepflow/server/vendor/github.com/deepflowio/deepflow/message/trident/trident.pb.go:13646 +0x56
google.golang.org/protobuf/internal/impl.legacyMarshal({{}, {0x5cf4230, 0xc05ee98070}, {0x0, 0x0, 0x0}, 0x0})
	/home/jiekun/repo/github.com/deepflow/server/vendor/google.golang.org/protobuf/internal/impl/legacy_message.go:402 +0xa2
google.golang.org/protobuf/proto.MarshalOptions.marshal({{}, 0xb8?, 0x0, 0x0}, {0x0, 0x0, 0x0}, {0x5cf4230, 0xc05ee98070})
	/home/jiekun/repo/github.com/deepflow/server/vendor/google.golang.org/protobuf/proto/encode.go:166 +0x27b
google.golang.org/protobuf/proto.MarshalOptions.MarshalAppend({{}, 0xa0?, 0x4b?, 0xe7?}, {0x0, 0x0, 0x0}, {0x5c6c860?, 0xc05ee98070?})
	/home/jiekun/repo/github.com/deepflow/server/vendor/google.golang.org/protobuf/proto/encode.go:125 +0x79
github.com/golang/protobuf/proto.marshalAppend({0x0, 0x0, 0x0}, {0x5c9ae80?, 0x0?}, 0x80?)
	/home/jiekun/repo/github.com/deepflow/server/vendor/github.com/golang/protobuf/proto/wire.go:40 +0xa5
github.com/golang/protobuf/proto.Marshal(...)
	/home/jiekun/repo/github.com/deepflow/server/vendor/github.com/golang/protobuf/proto/wire.go:23
google.golang.org/grpc/encoding/proto.codec.Marshal({}, {0x4e74ba0, 0x0})
	/home/jiekun/repo/github.com/deepflow/server/vendor/google.golang.org/grpc/encoding/proto/proto.go:45 +0x4e
google.golang.org/grpc.encode({0x7fa6e1a6cf98?, 0x9bc5780?}, {0x4e74ba0?, 0x0?})
	/home/jiekun/repo/github.com/deepflow/server/vendor/google.golang.org/grpc/rpc_util.go:596 +0x44
google.golang.org/grpc.(*Server).sendResponse(0xc005095c20, {0x5ce4960, 0xc000007a00}, 0xc05ee96000, {0x4e74ba0?, 0x0}, {0x0, 0x0}, 0x0?, {0x0, ...})
	/home/jiekun/repo/github.com/deepflow/server/vendor/google.golang.org/grpc/server.go:1107 +0x1b4
google.golang.org/grpc.(*Server).processUnaryRPC(0xc005095c20, {0x5ce4960, 0xc000007a00}, 0xc05ee96000, 0xc0019be960, 0x93a0330, 0x0)
	/home/jiekun/repo/github.com/deepflow/server/vendor/google.golang.org/grpc/server.go:1378 +0xde9
google.golang.org/grpc.(*Server).handleStream(0xc005095c20, {0x5ce4960, 0xc000007a00}, 0xc05ee96000, 0x0)
	/home/jiekun/repo/github.com/deepflow/server/vendor/google.golang.org/grpc/server.go:1704 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/home/jiekun/repo/github.com/deepflow/server/vendor/google.golang.org/grpc/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/jiekun/repo/github.com/deepflow/server/vendor/google.golang.org/grpc/server.go:963 +0x28a
```

### How to reproduce

1. build with `main` branch (`e316d1d0f2f86a7d0b4f13c08d7bfa5d7f4c1528`).
    - `cd server`
    - `CGO_ENABLED=0 GOOS=linux GOARCH=amd64 make -e BINARY_SUFFIX=.amd64`
2. build a docker image.
    - `docker build --network host -t deepflow-ce:dev.v1.0.0 .`
3. load the image into my minikube (It might not be necessary. Maybe you could try it with public image registry and jump to step-4).
    - `minikube image load deepflow-ce:dev.v1.0.0`
4. update `deepflow-server` deployment.
    - `kubectl edit deployment/deepflow-server`

I have the following fields edited:
```yaml
      ...
      containers:
        - name: deepflow-server
          # before
          image: registry.cn-hongkong.aliyuncs.com/deepflow-ce/deepflow-server:v6.3.5
          # after
          image: deepflow-ce:dev.v1.0.0
          ...
          
          # before
          imagePullPolicy: Always
          # after
          imagePullPolicy: Never          
      ...
```

The server went up for a while, I can query and see the graph on Grafana. But then it crashed and I got the panic log above.

I repeat the steps above with tag `v6.3.5` and everything looks fine (for at least couple hours).

### DeepFlow version

```bash
➜  deepflow kubectl exec -it -n deepflow deploy/deepflow-server -- deepflow-server -v
2023/08/16 17:58:23 ENV K8S_NODE_NAME_FOR_DEEPFLOW=minikube; K8S_NODE_IP_FOR_DEEPFLOW=192.168.49.2; K8S_POD_NAME_FOR_DEEPFLOW=deepflow-server-859b488549-5fkfn; K8S_POD_IP_FOR_DEEPFLOW=10.244.0.70; K8S_NAMESPACE_FOR_DEEPFLOW=deepflow
Name: deepflow-server community edition
Branch: 
CommitID: fc3c665be05c57d02b75a216cb6e81b4dd285bcd
RevCount: 8721
Compiler: go version go1.19 linux/amd64
CompileTime: 2023-08-16 16:47:25

➜  deepflow kubectl exec -it -n deepflow ds/deepflow-agent -- deepflow-agent -v
Defaulted container "deepflow-agent" out of: deepflow-agent, configure-sysctl (init)
8721-fc3c665be05c57d02b75a216cb6e81b4dd285bcd
Name: deepflow-agent community edition
Branch: v6.3.5
CommitId: fc3c665be05c57d02b75a216cb6e81b4dd285bcd
RevCount: 8721
Compiler: rustc 1.71.0 (8ede3aae2 2023-07-12)
CompileTime: 2023-08-11 06:58:09
```

### DeepFlow agent list

N/A

### Kubernetes CNI

N/A

### Operation-System/Kernel version

```
➜  deepflow awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release
"Ubuntu 20.04.6 LTS"
➜  deepflow uname -r 
5.15.0-78-generic
```

### Anything else
In order to try DeepFlow, I have OTel demo deployed.
```
helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
helm install my-otel-demo open-telemetry/opentelemetry-demo
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by lzf575** [comment]
latest fixed
