### ISSUE TITLE
[BUG] Panic when exporting with OTLP

### ISSUE THREAD

**Issue by jiekun** [deepflowio/deepflow#4542]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

We got logs with v6.40.0 otlp exporter:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4716ca]

goroutine 24783 [running]:
go.opentelemetry.io/collector/pdata/internal/data/protogen/common/v1.(*AnyValue_StringValue).MarshalToSizedBuffer(0xc2c93f4d80, {0xc2c95bc1d7, 0x9?, 0xe?})
	/home/jiekun/repo/github.com/deepflow/server/vendor/go.opentelemetry.io/collector/pdata/internal/data/protogen/common/v1/common.pb.go:499 +0x78
go.opentelemetry.io/collector/pdata/internal/data/protogen/common/v1.(*AnyValue_StringValue).MarshalTo(0x2?, {0xc2c95bc1d7?, 0xc00203d68c?, 0x2?})
	/home/jiekun/repo/github.com/deepflow/server/vendor/go.opentelemetry.io/collector/pdata/internal/data/protogen/common/v1/common.pb.go:493 +0x6a
go.opentelemetry.io/collector/pdata/internal/data/protogen/common/v1.(*AnyValue).MarshalToSizedBuffer(0xc2c9381e50, {0xc2c95b4000, 0x81dd, 0x10853})
	/home/jiekun/repo/github.com/deepflow/server/vendor/go.opentelemetry.io/collector/pdata/internal/data/protogen/common/v1/common.pb.go:483 +0x99
go.opentelemetry.io/collector/pdata/internal/data/protogen/common/v1.(*KeyValue).MarshalToSizedBuffer(0xc2c9381e40, {0xc2c95b4000, 0x81dd, 0x10853})
	/home/jiekun/repo/github.com/deepflow/server/vendor/go.opentelemetry.io/collector/pdata/internal/data/protogen/common/v1/common.pb.go:700 +0x3a
go.opentelemetry.io/collector/pdata/internal/data/protogen/trace/v1.(*Span).MarshalToSizedBuffer(0xc2c8501520, {0xc2c95b4000, 0x82b1, 0x10853})
	/home/jiekun/repo/github.com/deepflow/server/vendor/go.opentelemetry.io/collector/pdata/internal/data/protogen/trace/v1/trace.pb.go:1056 +0xc26
go.opentelemetry.io/collector/pdata/internal/data/protogen/trace/v1.(*ScopeSpans).MarshalToSizedBuffer(0xc2c6619dc0, {0xc2c95b4000, 0x82b1, 0x10853})
	/home/jiekun/repo/github.com/deepflow/server/vendor/go.opentelemetry.io/collector/pdata/internal/data/protogen/trace/v1/trace.pb.go:956 +0x23c
go.opentelemetry.io/collector/pdata/internal/data/protogen/trace/v1.(*ResourceSpans).MarshalToSizedBuffer(0xc2c824ade0, {0xc2c95b4000, 0x82b1, 0x10853})
	/home/jiekun/repo/github.com/deepflow/server/vendor/go.opentelemetry.io/collector/pdata/internal/data/protogen/trace/v1/trace.pb.go:902 +0x25c
go.opentelemetry.io/collector/pdata/internal/data/protogen/collector/trace/v1.(*ExportTraceServiceRequest).MarshalToSizedBuffer(0xc2c09f8d08, {0xc2c95b4000, 0x10853, 0x10853})
	/home/jiekun/repo/github.com/deepflow/server/vendor/go.opentelemetry.io/collector/pdata/internal/data/protogen/collector/trace/v1/trace_service.pb.go:351 +0xac
go.opentelemetry.io/collector/pdata/internal/data/protogen/collector/trace/v1.(*ExportTraceServiceRequest).Marshal(0xc000b00000?)
	/home/jiekun/repo/github.com/deepflow/server/vendor/go.opentelemetry.io/collector/pdata/internal/data/protogen/collector/trace/v1/trace_service.pb.go:331 +0x56
google.golang.org/protobuf/internal/impl.legacyMarshal({{}, {0x69344b0, 0xc2c9453220}, {0x0, 0x0, 0x0}, 0x0})
	/home/jiekun/repo/github.com/deepflow/server/vendor/google.golang.org/protobuf/internal/impl/legacy_message.go:402 +0xa2
google.golang.org/protobuf/proto.MarshalOptions.marshal({{}, 0xf8?, 0x0, 0x0}, {0x0, 0x0, 0x0}, {0x69344b0, 0xc2c9453220})
	/home/jiekun/repo/github.com/deepflow/server/vendor/google.golang.org/protobuf/proto/encode.go:166 +0x27b
google.golang.org/protobuf/proto.MarshalOptions.MarshalAppend({{}, 0x40?, 0x3f?, 0x9f?}, {0x0, 0x0, 0x0}, {0x68bbe20?, 0xc2c9453220?})
	/home/jiekun/repo/github.com/deepflow/server/vendor/google.golang.org/protobuf/proto/encode.go:125 +0x79
github.com/golang/protobuf/proto.marshalAppend({0x0, 0x0, 0x0}, {0x7f2841453610?, 0xc2c09f8d08?}, 0x40?)
	/home/jiekun/repo/github.com/deepflow/server/vendor/github.com/golang/protobuf/proto/wire.go:40 +0xa5
github.com/golang/protobuf/proto.Marshal(...)
	/home/jiekun/repo/github.com/deepflow/server/vendor/github.com/golang/protobuf/proto/wire.go:23
google.golang.org/grpc/encoding/proto.codec.Marshal({}, {0x59f3f40, 0xc2c09f8d08})
	/home/jiekun/repo/github.com/deepflow/server/vendor/google.golang.org/grpc/encoding/proto/proto.go:45 +0x4e
google.golang.org/grpc.encode({0x7f284247abf0?, 0xb193930?}, {0x59f3f40?, 0xc2c09f8d08?})
	/home/jiekun/repo/github.com/deepflow/server/vendor/google.golang.org/grpc/rpc_util.go:633 +0x44
google.golang.org/grpc.prepareMsg({0x59f3f40?, 0xc2c09f8d08?}, {0x7f284247abf0?, 0xb193930?}, {0x0, 0x0}, {0x0, 0x0})
	/home/jiekun/repo/github.com/deepflow/server/vendor/google.golang.org/grpc/stream.go:1765 +0xd2
google.golang.org/grpc.(*clientStream).SendMsg(0xc2c302cb40, {0x59f3f40?, 0xc2c09f8d08})
	/home/jiekun/repo/github.com/deepflow/server/vendor/google.golang.org/grpc/stream.go:887 +0xfd
google.golang.org/grpc.invoke({0x68f8668?, 0xc0118ac810?}, {0x5f85f07?, 0x40dcff?}, {0x59f3f40, 0xc2c09f8d08}, {0x59f4080, 0xc2c09f8d20}, 0xc2c92f2a10?, {0x0, ...})
	/home/jiekun/repo/github.com/deepflow/server/vendor/google.golang.org/grpc/call.go:75 +0xa8
google.golang.org/grpc.(*ClientConn).Invoke(0xc06dffd400, {0x68f8668, 0xc0118ac810}, {0x5f85f07, 0x3b}, {0x59f3f40, 0xc2c09f8d08}, {0x59f4080, 0xc2c09f8d20}, {0x0, ...})
	/home/jiekun/repo/github.com/deepflow/server/vendor/google.golang.org/grpc/call.go:42 +0x2e5
go.opentelemetry.io/collector/pdata/internal/data/protogen/collector/trace/v1.(*traceServiceClient).Export(0xc06c7c2cd8, {0x68f8668, 0xc0118ac810}, 0x0?, {0x0, 0x0, 0x0})
	/home/jiekun/repo/github.com/deepflow/server/vendor/go.opentelemetry.io/collector/pdata/internal/data/protogen/collector/trace/v1/trace_service.pb.go:271 +0xc9
go.opentelemetry.io/collector/pdata/ptrace/ptraceotlp.(*grpcClient).Export(0xffffffffffffffff?, {0x68f8668?, 0xc0118ac810?}, {0xc2c824b3e0?}, {0x0?, 0xd354670049213665?, 0x0?})
	/home/jiekun/repo/github.com/deepflow/server/vendor/go.opentelemetry.io/collector/pdata/ptrace/ptraceotlp/grpc.go:48 +0x30
github.com/deepflowio/deepflow/server/ingester/flow_log/exporters/otlp_exporter.(*OtlpExporter).grpcExport(0xc0007f0c00, {0x68f8668, 0xc0118ac810}, 0x6, {0x5a8aae0?})
	/home/jiekun/repo/github.com/deepflow/server/ingester/flow_log/exporters/otlp_exporter/exporter.go:204 +0x218
github.com/deepflowio/deepflow/server/ingester/flow_log/exporters/otlp_exporter.(*OtlpExporter).queueProcess(0xc0007f0c00, 0x6)
	/home/jiekun/repo/github.com/deepflow/server/ingester/flow_log/exporters/otlp_exporter/exporter.go:176 +0x3e6
created by github.com/deepflowio/deepflow/server/ingester/flow_log/exporters/otlp_exporter.(*OtlpExporter).Start
	/home/jiekun/repo/github.com/deepflow/server/ingester/flow_log/exporters/otlp_exporter/exporter.go:138 +0x105
```

The root cause is still under investigation. I'd like to paste the log here to see if someone has similar issue.

### How to reproduce

N/A

### DeepFlow version

v6.40.0

### DeepFlow agent list

N/A

### Kubernetes CNI

N/A

### Operation-System/Kernel version

N/A

### Anything else

N/A

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jiekun** [comment]
Another panic log when writing to CK:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x46d901]

goroutine 35824 [running]:
github.com/ClickHouse/clickhouse-go/v2/lib/column.(*LowCardinality).AppendRow(0xc0968c8fc0, {0x518f600, 0xc25421b060})
	/home/jiekun/repo/github.com/deepflow/server/vendor/github.com/ClickHouse/clickhouse-go/v2/lib/column/lowcardinality.go:149 +0x11b
github.com/ClickHouse/clickhouse-go/v2/lib/proto.(*Block).Append(0xc096f59ec0, {0xc0187ea000?, 0x6a, 0xb197320?})
	/home/jiekun/repo/github.com/deepflow/server/vendor/github.com/ClickHouse/clickhouse-go/v2/lib/proto/block.go:64 +0x19a
github.com/ClickHouse/clickhouse-go/v2.(*batch).Append(0xc0ac60e320, {0xc0187ea000?, 0x6a?, 0x100?})
	/home/jiekun/repo/github.com/deepflow/server/vendor/github.com/ClickHouse/clickhouse-go/v2/conn_batch.go:135 +0x34
github.com/deepflowio/deepflow/server/libs/ckdb.(*Block).WriteAll(...)
	/home/jiekun/repo/github.com/deepflow/server/libs/ckdb/ckdb.go:47
github.com/deepflowio/deepflow/server/ingester/pkg/ckwriter.(*CKWriter).writeItems(0xc0098078c0, 0x0, 0x0, {0xc01d9d8000, 0x7d000, 0x46c399?})
	/home/jiekun/repo/github.com/deepflow/server/ingester/pkg/ckwriter/ckwriter.go:357 +0x4b6
github.com/deepflowio/deepflow/server/ingester/pkg/ckwriter.(*CKWriter).Write(0xc0098078c0, 0x0, {0xc01d9d8000?, 0x7d000, 0x7d000})
	/home/jiekun/repo/github.com/deepflow/server/ingester/pkg/ckwriter/ckwriter.go:274 +0x9b
github.com/deepflowio/deepflow/server/ingester/pkg/ckwriter.(*CKWriter).queueProcess(0xc0098078c0, 0x0)
	/home/jiekun/repo/github.com/deepflow/server/ingester/pkg/ckwriter/ckwriter.go:238 +0x5c5
created by github.com/deepflowio/deepflow/server/ingester/pkg/ckwriter.(*CKWriter).Run
	/home/jiekun/repo/github.com/deepflow/server/ingester/pkg/ckwriter/ckwriter.go:190 +0x30
```

It might be not relevent with the otlp exporter issue, but since we are using v6.40.0 so I would like to post them here, together.

**Comment by jiekun** [comment]
```
goroutine 24249 [running]:
github.com/deepflowio/deepflow/server/ingester/flow_log/log_data.(*L7FlowLog).GenerateNewFlowTags(0xc0b4933180, 0xc000151340)
	/home/jiekun/repo/github.com/deepflow/server/ingester/flow_log/log_data/l7_flow_log.go:639 +0xf3c
github.com/deepflowio/deepflow/server/ingester/flow_log/decoder.(*Decoder).sendProto(0xc008536b40, 0xc1712c56c0)
	/home/jiekun/repo/github.com/deepflow/server/ingester/flow_log/decoder/decoder.go:312 +0x19b
github.com/deepflowio/deepflow/server/ingester/flow_log/decoder.(*Decoder).handleProtoLog(0xc008536b40, 0xc00d52be50)
	/home/jiekun/repo/github.com/deepflow/server/ingester/flow_log/decoder/decoder.go:201 +0x31
github.com/deepflowio/deepflow/server/ingester/flow_log/decoder.(*Decoder).Run(0xc008536b40)
	/home/jiekun/repo/github.com/deepflow/server/ingester/flow_log/decoder/decoder.go:153 +0x5fc
created by github.com/deepflowio/deepflow/server/ingester/flow_log/flow_log.(*Logger).Start
	/home/jiekun/repo/github.com/deepflow/server/ingester/flow_log/flow_log/flow_log.go:304 +0x87
panic: runtime error: index out of range [4] with length 4
```

**Comment by jiekun** [comment]
```
panic: runtime error: index out of range [3] with length 3

goroutine 24244 [running]:
github.com/deepflowio/deepflow/server/ingester/flow_log/log_data.(*L7FlowLog).GenerateNewFlowTags(0xc09257ee00, 0xc000af1290)
	/home/jiekun/repo/github.com/deepflow/server/ingester/flow_log/log_data/l7_flow_log.go:639 +0xf3c
github.com/deepflowio/deepflow/server/ingester/flow_log/decoder.(*Decoder).sendProto(0xc004f46fc0, 0xc11cf24a80)
	/home/jiekun/repo/github.com/deepflow/server/ingester/flow_log/decoder/decoder.go:312 +0x19b
github.com/deepflowio/deepflow/server/ingester/flow_log/decoder.(*Decoder).handleProtoLog(0xc004f46fc0, 0xc00e807e50)
	/home/jiekun/repo/github.com/deepflow/server/ingester/flow_log/decoder/decoder.go:201 +0x31
github.com/deepflowio/deepflow/server/ingester/flow_log/decoder.(*Decoder).Run(0xc004f46fc0)
	/home/jiekun/repo/github.com/deepflow/server/ingester/flow_log/decoder/decoder.go:153 +0x5fc
created by github.com/deepflowio/deepflow/server/ingester/flow_log/flow_log.(*Logger).Start
	/home/jiekun/repo/github.com/deepflow/server/ingester/flow_log/flow_log/flow_log.go:304 +0x87
panic: runtime error: index out of range [3] with length 3
```
Server is keep crashing due to the same issue. @lzf575

**Comment by fidoooooowang** [comment]
We have similar problem with v6.4.0

panic: runtime error: index out of range [4] with length 4

goroutine 36536 [running]:
github.com/deepflowio/deepflow/server/ingester/flow_log/log_data.(*L7FlowLog).GenerateNewFlowTags(0xc085f92000, 0xc000166dc0)
	/home/runnerx/actions-runner/_work/deepflow/deepflow/server/ingester/flow_log/log_data/l7_flow_log.go:639 +0xf3c
github.com/deepflowio/deepflow/server/ingester/flow_log/decoder.(*Decoder).sendProto(0xc00d986360, 0xc10f4f56c0)
	/home/runnerx/actions-runner/_work/deepflow/deepflow/server/ingester/flow_log/decoder/decoder.go:312 +0x19b
github.com/deepflowio/deepflow/server/ingester/flow_log/decoder.(*Decoder).handleProtoLog(0xc00d986360, 0xc002b92e50)
	/home/runnerx/actions-runner/_work/deepflow/deepflow/server/ingester/flow_log/decoder/decoder.go:201 +0x31
github.com/deepflowio/deepflow/server/ingester/flow_log/decoder.(*Decoder).Run(0xc00d986360)
	/home/runnerx/actions-runner/_work/deepflow/deepflow/server/ingester/flow_log/decoder/decoder.go:153 +0x5fc
created by github.com/deepflowio/deepflow/server/ingester/flow_log/flow_log.(*Logger).Start
	/home/runnerx/actions-runner/_work/deepflow/deepflow/server/ingester/flow_log/flow_log/flow_log.go:304 +0x87
