### ISSUE TITLE
[BUG] deepflow-server 6.4.7 - fatal error: concurrent map writes

### ISSUE THREAD

**Issue by dirtyren** [deepflowio/deepflow#5195]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Server

### What you expected to happen

After updating from 6.4.5 to 6.4.7 deepflow-server is restarting trhowing the error fatal error: concurrent map writes

### How to reproduce

Update from 6.4.5 to 6.4.7 using helm

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by dirtyren** [comment]
```
2024-01-09 16:18:49.553 [GIN] 10.254.138.4 POST /v1/query/ 200 34.332397ms
2024-01-09 16:18:49.649 [GIN] 127.0.0.1 GET /v1/data-sources/?type=flow&name=1m 200 1.835824ms
2024-01-09 16:18:49.655 [GIN] 127.0.0.1 GET /v1/data-sources/?type=flow&name=1m 200 2.3807ms
2024-01-09 16:18:49.660 [GIN] 127.0.0.1 GET /v1/data-sources/?type=flow&name=1m 200 2.374703ms
2024-01-09 16:18:49.663 [GIN] 127.0.0.1 GET /v1/data-sources/?type=flow&name=1m 200 1.917226ms
fatal error: concurrent map writes

goroutine 4304 [running]:
github.com/deepflowio/deepflow/server/querier/engine/clickhouse/metrics.GetMetrics({0xc05381fdb0?, 0x31000000047a4ab4?}, {0xc055a26815, 0xc}, {0xc085084738, 0x13}, {0x4da55e0?, 0xc00097cb50?})
        /home/runnerx/actions-runner/_work/deepflow/deepflow/server/querier/engine/clickhouse/metrics/metrics.go:179 +0xc2f
github.com/deepflowio/deepflow/server/querier/engine/clickhouse/metrics.GetAggMetrics({0xc05381fdb0?, 0xc000335260?}, {0xc055a26815, 0xc}, {0xc085084738, 0x13}, {0x63d5950, 0xc055d8efc0})
        /home/runnerx/actions-runner/_work/deepflow/deepflow/server/querier/engine/clickhouse/metrics/metrics.go:111 +0x18d
github.com/deepflowio/deepflow/server/querier/engine/clickhouse.GetAggFunc({0xc05381fdb7, 0x3}, {0xc053878880?, 0x1, 0x1}, {0x0, 0x0}, {0xc055a26815, 0xc}, {0xc085084738, .
```

**Comment by dirtyren** [comment]
Just to add another information, I removed deepflow 6.4.7 and reisntalled from scratch 6.4.5 and deepflow is working perfectly.

**Comment by icylord** [comment]
got the same issue after upgrading to v6.4.7 too
