### ISSUE TITLE
[BUG] dashboard A pplication-Out-Of-The-Box panel error

### ISSUE THREAD

**Issue by fyuan1316** [deepflowio/deepflow#5659]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Grafana Dashbaord

### What you expected to happen

异常比例 panel 可以正常工作

### How to reproduce

直接使用 panel 无数据加载
选择 edit 后，报错 An unexpected error happened

### DeepFlow version

version: 6.3
app:
    image /deepflow-ce/deepflow-app:v6.3-130
agent:
    image: /deepflow-ce/deepflow-agent:v6.3-9183
    image: /deepflow-ce/deepflow-agent:v6.3-9222
server
    image: deepflow-ce/deepflow-server:v6.3-9220

### Operation-System/Kernel version

```
Linux asm-yuanfang-p1693-0272 4.18.0-425.3.1.el8.x86_64 #1 SMP Fri Sep 30 11:45:06 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### Anything else

```
An unexpected error happened
详情
Error: "palette-classic-by-name" not found in: fixed,thresholds,palette-classic,continuous-GrYlRd,continuous-RdYlGr,continuous-BlYlRd,continuous-YlRd,continuous-BlPu,continuous-YlBl,continuous-blues,continuous-reds,continuous-greens,continuous-purples

    at te (https://192.168.133.8/clusters/region/grafana/public/build/7911.ea59f714e69d0d502e5c.js:4815:3701)
    at div
    at div
    at d (https://192.168.133.8/clusters/region/grafana/public/build/7911.ea59f714e69d0d502e5c.js:1475:20)
    at div
    at div
    at https://192.168.133.8/clusters/region/grafana/public/build/7911.ea59f714e69d0d502e5c.js:6035:17312
    at div
    at div
    at div
    at ne (https://192.168.133.8/clusters/region/grafana/public/build/215.c1c0320c66de376bf22b.js:125:13314)
    at r (https://192.168.133.8/clusters/region/grafana/public/build/7911.ea59f714e69d0d502e5c.js:475:3184)
    at div
    at div
    at wa (https://192.168.133.8/clusters/region/grafana/public/build/DashboardPage.1e7a423a51eb0f3b27eb.js:65:4131)
    at div
    at div
    at ar (https://192.168.133.8/clusters/region/grafana/public/build/DashboardPage.1e7a423a51eb0f3b27eb.js:188:21)
    at div
    at c (https://192.168.133.8/clusters/region/grafana/public/build/1725.61e439b7c07502f68e23.js:1:2293)
    at div
    at c (https://192.168.133.8/clusters/region/grafana/public/build/1725.61e439b7c07502f68e23.js:1:4277)
    at J (https://192.168.133.8/clusters/region/grafana/public/build/1725.61e439b7c07502f68e23.js:1:9639)
    at div
    at div
    at div
    at y (https://192.168.133.8/clusters/region/grafana/public/build/7911.ea59f714e69d0d502e5c.js:4847:1016)
    at cs (https://192.168.133.8/clusters/region/grafana/public/build/DashboardPage.1e7a423a51eb0f3b27eb.js:324:1093)
    at xt (https://192.168.133.8/clusters/region/grafana/public/build/215.c1c0320c66de376bf22b.js:154:127638)
    at WithTheme(Connect(cs))
    at nt (https://192.168.133.8/clusters/region/grafana/public/build/DashboardPage.1e7a423a51eb0f3b27eb.js:387:424)
    at DashboardPage
    at xt (https://192.168.133.8/clusters/region/grafana/public/build/215.c1c0320c66de376bf22b.js:154:127638)
    at Suspense
    at i (https://192.168.133.8/clusters/region/grafana/public/build/7911.ea59f714e69d0d502e5c.js:1270:169)
    at cm (https://192.168.133.8/clusters/region/grafana/public/build/7911.ea59f714e69d0d502e5c.js:9759:330)
    at Kt (https://192.168.133.8/clusters/region/grafana/public/build/215.c1c0320c66de376bf22b.js:158:13496)
    at Kt (https://192.168.133.8/clusters/region/grafana/public/build/215.c1c0320c66de376bf22b.js:158:15691)
    at main
    at dc (https://192.168.133.8/clusters/region/grafana/public/build/7911.ea59f714e69d0d502e5c.js:9720:2498)
    at Kt (https://192.168.133.8/clusters/region/grafana/public/build/215.c1c0320c66de376bf22b.js:158:9783)
    at div
    at l (https://192.168.133.8/clusters/region/grafana/public/build/7911.ea59f714e69d0d502e5c.js:2525:4092)
    at p (https://192.168.133.8/clusters/region/grafana/public/build/215.c1c0320c66de376bf22b.js:32:52076)
    at i (https://192.168.133.8/clusters/region/grafana/public/build/7911.ea59f714e69d0d502e5c.js:5204:16801)
    at i (https://192.168.133.8/clusters/region/grafana/public/build/7911.ea59f714e69d0d502e5c.js:1270:169)
    at f (https://192.168.133.8/clusters/region/grafana/public/build/7911.ea59f714e69d0d502e5c.js:1270:720)
    at S (https://192.168.133.8/clusters/region/grafana/public/build/215.c1c0320c66de376bf22b.js:154:125332)
    at Am (https://192.168.133.8/clusters/region/grafana/public/build/7911.ea59f714e69d0d502e5c.js:9772:122)
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by 1473371932** [comment]
原因为 grafana init 镜像版本导致，例如当前 DeepFlow 版本为 v6.4，则 init 镜像 tag 需对应此版本
