### ISSUE TITLE
[BUG][v6.5.2] server runs panic

### ISSUE THREAD

**Issue by rosenlo** [deepflowio/deepflow#5933]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Server

### What you expected to happen

normal

### How to reproduce

```
unexpected fault address 0x1
fatal error: fault
[signal SIGBUS: bus error code=0x1 addr=0x1 pc=0x3a948a0]

goroutine 208542 [running]:
runtime.throw({0x5476113?, 0x42a4fcf6b0?})
        /usr/local/go/src/runtime/panic.go:1047 +0x40 fp=0x41584f9a60 sp=0x41584f9a30 pc=0x4448e0
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:836 +0xa4 fp=0x41584f9a90 sp=0x41584f9a60 pc=0x45c154
github.com/deepflowio/deepflow/server/libs/grpc.(*PlatformInfoTable).IPV4InfoStat(0x41584f9b48?, {0x44d4dc0?, 0x42a4ef6c98?})
        /go/release/server/libs/grpc/grpc_platformdata.go:457 +0xc0 fp=0x41584f9b00 sp=0x41584f9aa0 pc=0x3a948a0
github.com/deepflowio/deepflow/server/libs/grpc.(*PlatformInfoTable).queryIPV4Infos(0x4009c9c180, 0x1212, 0xa754c10)
        /go/release/server/libs/grpc/grpc_platformdata.go:477 +0x88 fp=0x41584f9b50 sp=0x41584f9b00 pc=0x3a94a28
github.com/deepflowio/deepflow/server/libs/grpc.(*PlatformInfoTable).QueryIPV4Infos(0x4287c14fd0?, 0x1212, 0x42?)
        /go/release/server/libs/grpc/grpc_platformdata.go:243 +0x2c fp=0x41584f9b90 sp=0x41584f9b50 pc=0x3a933bc
github.com/deepflowio/deepflow/server/libs/grpc.(*PlatformInfoTable).updatePodIps(0x4009c9c180, {0x42dc100000, 0x6edf, 0x999fe00?})
        /go/release/server/libs/grpc/grpc_platformdata.go:1620 +0x538 fp=0x41584f9d10 sp=0x41584f9b90 pc=0x3a9e9c8
github.com/deepflowio/deepflow/server/libs/grpc.(*PlatformInfoTable).updateOthers(0x4009c9c180, 0x4276ae8300)
        /go/release/server/libs/grpc/grpc_platformdata.go:989 +0x90 fp=0x41584f9d60 sp=0x41584f9d10 pc=0x3a9a3f0
github.com/deepflowio/deepflow/server/libs/grpc.(*PlatformInfoTable).ReloadMaster(0x4009c9c180)
        /go/release/server/libs/grpc/grpc_platformdata.go:1145 +0x694 fp=0x41584f9f30 sp=0x41584f9d60 pc=0x3a9b314
github.com/deepflowio/deepflow/server/libs/grpc.NewPlatformInfoTable.func1()
        /go/release/server/libs/grpc/grpc_platformdata.go:429 +0x28 fp=0x41584f9f90 sp=0x41584f9f30 pc=0x3a944f8
github.com/deepflowio/deepflow/server/libs/grpc.(*GrpcSession).run(0x4018a51020)
        /go/release/server/libs/grpc/grpc_session.go:119 +0x30 fp=0x41584f9fb0 sp=0x41584f9f90 pc=0x3aa2980
github.com/deepflowio/deepflow/server/libs/grpc.(*GrpcSession).Start.func1()
        /go/release/server/libs/grpc/grpc_session.go:127 +0x28 fp=0x41584f9fd0 sp=0x41584f9fb0 pc=0x3aa2ab8
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x41584f9fd0 sp=0x41584f9fd0 pc=0x4790a4
created by github.com/deepflowio/deepflow/server/libs/grpc.(*GrpcSession).Start
        /go/release/server/libs/grpc/grpc_session.go:127 +0x68

```

### DeepFlow version

```
Name: deepflow-server community edition
Branch: master
CommitID: 5233724cd98170911803f1401aae19c9b6712a48
RevCount: 10483
Compiler: go version go1.19.10 linux/arm64
CompileTime: 2024-03-19 04:53:30
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by lzf575** [comment]
@rosenlo  请使用 v6.5 版本，确认 deepflow-server -v 是最近时间，看看还有问题么

**Comment by lzf575** [comment]
在这个commint 解决了， c3f7d3173cfab8021971834e7f40e80a588f9e03
